import React, { ReactNode } from "react";
import Head from "next/head";
import TopBar from "../TopBar";
import { StyledMainWrapper } from "./styles";
import SideMenu from "../SideMenu";

type layoutType = {
  children: ReactNode;
};

const Layout: React.FC<layoutType> = ({ children }) => {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link
          rel='icon'
          href='https://www.svgrepo.com/show/396914/letter-y.svg'
        />
      </Head>
      <StyledMainWrapper>
        <TopBar />
        <SideMenu />
        {children}
      </StyledMainWrapper>
    </>
  );
};

export default Layout;
